version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: friendlysquad_website
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3001:3001
# networks:
#   stagingnetwork:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.28.0.0/16
#           gateway: 65.21.152.12
